version: '3'
services:
  postgres:
    image: postgres:16-bullseye
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "4000:3000"
    # depends_on:
    #   - postgres
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
    - "80:80"
